openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /tables:
    get:
      operationId: getTables
      tags:
        - Tables
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/table"
          description: Tables has been retrieved successfully
    post:
      operationId: createTable
      tags:
        - Tables
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/table"
      responses:
        201:
          $ref: "#/components/responses/201"
  /tables/{tableId}:
    get:
      operationId: getTable
      tags:
        - Tables
      parameters:
        - name: tableId
          in: path
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        200:
          description: Table has been retrieved successfully
    put:
      operationId: updateTable
      tags:
        - Tables
      parameters:
        - name: tableId
          in: path
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/table"
      responses:
        200:
          description: Table has been updated successfully
    delete:
      operationId: deleteTable
      tags:
        - Tables
      parameters:
        - name: tableId
          in: path
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        200:
          description: Tables has been deleted successfully
  /categories:
    get:
      operationId: getCategories
      tags:
        - Categories
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/category"
          description: Categories have been retrieved successfully
    post:
      operationId: createCategory
      tags:
        - Categories
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/category"
      responses:
        201:
          $ref: "#/components/responses/201"
  /categories/{categoryId}:
    get:
      operationId: getCategory
      tags:
        - Categories
      parameters:
        - name: categoryId
          in: path
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        200:
          description: Category has been retrieved successfully
    put:
      operationId: updateCategory
      tags:
        - Categories
      parameters:
        - name: categoryId
          in: path
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/category"
      responses:
        200:
          description: Category has been updated successfully
    delete:
      operationId: deleteCategory
      tags:
        - Categories
      parameters:
        - name: categoryId
          in: path
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        200:
          description: Category has been deleted successfully
  /articles:
    get:
      operationId: getArticles
      tags:
        - Articles
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/article"
          description: Articles have been retrieved successfully
    post:
      operationId: createArticle
      tags:
        - Articles
      parameters:
        - name: x-category-id
          in: header
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/article"
      responses:
        201:
          $ref: "#/components/responses/201"
  /articles/{articleId}:
    get:
      operationId: getArticle
      tags:
        - Articles
      parameters:
        - name: articleId
          in: path
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        200:
          description: Article has been retrieved successfully
    put:
      operationId: updateArticle
      tags:
        - Articles
      parameters:
        - name: articleId
          in: path
          schema:
            $ref: "#/components/schemas/id"
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/article"
      responses:
        200:
          description: Article has been updated successfully
    delete:
      operationId: deleteArticle
      tags:
        - Articles
      parameters:
        - name: articleId
          in: path
          schema:
            $ref: "#/components/schemas/id"
          required: true
      responses:
        200:
          description: Article has been deleted successfully
components:
  schemas:
    table:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        seatCount:
          type: integer
        active:
          type: boolean
    category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    article:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: number
        description:
          type: string
        picture:
          type: string
    id:
      type: integer
      format: int64
  responses:
    201:
      description: Data has been created successfully